version: "3.9"
services:
  web:
    build: ./web
    container_name: 'flask_app'
    command: python manage.py run -h 0.0.0.0
    restart: on-failure
    environment:
        - FLASK_APP=parser/app.py
        - FLASK_ENV=development
        - DATABASE_URL=postgresql://postgres:postgres@test_db:5432/flask_postgres
        - SQL_HOST=test_db
        - SQL_PORT=5432
        - DATABASE=postgres
        - CONFIG=test
    ports:
        - "5000:5000"
    volumes:
        - ./web:/app
    networks:
        - test_rabbitmq_flask
    depends_on:
        - test_db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq/
    networks:
        - test_rabbitmq_flask
  test_db:
    image: postgres:latest
    container_name: 'test_postgres_db'
    expose:
        - "5432"
    volumes:
        - test_postgres_db:/var/lib/postgresql/test_data/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=flask_postgres
    networks:
        - test_rabbitmq_flask
  consumer:
    build: ./web
    container_name: 'flask_consumer'
    command: python manage.py start_consume
    restart: on-failure
    environment:
        - FLASK_APP=parser/app.py
        - FLASK_ENV=development
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_postgres
        - SQL_HOST=db
        - SQL_PORT=5432
        - DATABASE=postgres
    volumes:
        - ./web:/app
    networks:
        - test_rabbitmq_flask
    links:
        - rabbitmq
    depends_on:
        - test_db
        - rabbitmq
networks:
  test_rabbitmq_flask:
    driver: bridge

volumes:
  test_postgres_db: